apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-service
    app: demo-guestbook-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    app: demo-guestbook-app
